{% set data = load_setup_py_data() %}

package:
  name: openalea.grapheditor
  version: {{ data.get('version') }}

source:
  path: ..

build:
  noarch: python
  preserve_egg_dir: True
  number: 0
  script: {{PYTHON}} setup.py install 

requirements:
  build:
    - python {{PY_VER}}
    - openalea.deploy
  run:
    - python
    - openalea.deploy
    - openalea.core
    - qtpy

test:
  imports:
    - openalea.grapheditor

about:
  home: {{ data.get('url') }}
  license: Cecill-c License
  summary: {{ data.get('description') }}

